local du = require("dutil")

du.default_copy = true

du.alias("fabricator-1", du.icons("__Krastorio2Assets__/icons/entities/advanced-assembling-machine.png", true), true)
du.alias("counterflow-heat-exchanger", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/classifier.png"}, true)
du.alias("destructive-distillation-tower", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/distilator.png"}, true)
du.alias("glassworks", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/glassworks-mk01.png"}, true)
du.alias("smithy", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/advanced-foundry-mk01.png"}, true)
du.alias("oil-refinery", du.icons{discard=true, name="__pypetroleumhandlinggraphics__/graphics/icons/hor-mk01.png"}, true)
du.alias("fuel-refinery", du.icons{discard=true, name="__base__/graphics/icons/oil-refinery.png"}, true)
du.alias("computer-1", du.icons("se/supercomputer-1"), true)
du.alias("computer-2", du.icons("se/supercomputer-2"), true)
du.alias("computer-3", du.icons("se/supercomputer-3"), true)
du.alias("computer-4", du.icons("se/supercomputer-4"), true)
du.alias("processor-1", du.icons("se/laser-laboratory"), true)
du.alias("process", du.icons("se/astronomic-catalogue-4"), true)
du.alias("dead-process", du.icons("se/material-catalogue-4"), true)
du.alias("combustion-generator", du.icons("__Krastorio2Assets__/icons/entities/gas-power-station.png", true), true)
du.alias("crystallizer", du.icons("__pycoalprocessinggraphics__/graphics/icons/desulfurizator-unit.png", true), true)
du.rename("environmental-insight", "se/catalogue/biological-insight")
du.rename("mechanical-insight", "se/catalogue/astronomic-insight")
du.rename("electromagnetic-insight", "se/catalogue/energy-insight")
du.rename("thalorain", "angels/bio/swamp-2&x32")
du.rename("thalorain-grain", "angels/bio/swamp-4&x32")
du.rename("sweet-thalorain-grain", "angels/bio/swamp-4&x32&#327fa8")
du.rename("thalorain-ferment", "angels/bio/solid-alginic-acid&x32")
du.rename("native-biofilm", "angels/bio/alien-pre-artifact-orange&x32")
du.rename("compost", "angels/bio/solid-compost&x32")
du.rename("saw", "angels/bio/solid-saw")
du.rename("nauvisworm", "worm")
du.rename("nauvisworm-egg-sack", "angels/bio/bacteria-anaerobic&x32")
du.rename("rich-soil", "angels/bio/solid-soil&x32")
du.rename("phosphoric-fertilizer", "angels/bio/solid-fruit&x32")
du.rename("nitrogenous-fertilizer", "angels/bio/solid-pips&x32")
du.rename("composter", "composter&x32")
du.rename("worm-meal", "angels/bio/cellulose-fiber&x32")
du.rename("green-algae", "angels/bio/algae-green&x32")
du.rename("outfall", "seafloor-pump-ico&x32")
du.rename("soil-extractor", "%__pycoalprocessinggraphics__/graphics/icons/soil-extractor-mk01.png")