local du = require("dutil")

du.default_copy = true

du.alias("fabricator-1", du.icons("__Krastorio2Assets__/icons/entities/advanced-assembling-machine.png", true), true)
du.alias("counterflow-heat-exchanger", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/classifier.png"}, true)
du.alias("destructive-distillation-tower", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/distilator.png"}, true)
du.alias("glassworks", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/glassworks-mk01.png"}, true)
du.alias("smithy", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/advanced-foundry-mk01.png"}, true)
du.alias("oil-refinery", du.icons{discard=true, name="__pypetroleumhandlinggraphics__/graphics/icons/hor-mk01.png"}, true)
du.alias("fuel-refinery", du.icons{discard=true, name="__base__/graphics/icons/oil-refinery.png"}, true)
du.alias("computer-1", du.icons("se/supercomputer-1"), true)
du.alias("computer-2", du.icons("se/supercomputer-2"), true)
du.alias("computer-3", du.icons("se/supercomputer-3"), true)
du.alias("computer-4", du.icons("se/supercomputer-4"), true)
du.alias("processor-1", du.icons("se/laser-laboratory"), true)
du.alias("process", du.icons("se/astronomic-catalogue-4"), true)
du.alias("dead-process", du.icons("se/material-catalogue-4"), true)
du.alias("combustion-generator", du.icons("__Krastorio2Assets__/icons/entities/gas-power-station.png", true), true)
du.alias("crystallizer", du.icons("__pycoalprocessinggraphics__/graphics/icons/desulfurizator-unit.png", true), true)
du.rename("environmental-insight", "se/catalogue/biological-insight")
du.rename("mechanical-insight", "se/catalogue/astronomic-insight")
du.rename("electromagnetic-insight", "se/catalogue/energy-insight")
du.rename("thalorain", "angelsbioprocessinggraphics.swamp-2&x32")
du.rename("thalorain-grain", "angelsbioprocessinggraphics.swamp-4&x32")
du.rename("sweet-thalorain-grain", "angelsbioprocessinggraphics.swamp-4&x32&#327fa8")
du.rename("thalorain-ferment", "angelsbioprocessinggraphics.solid-alginic-acid&x32")
du.rename("native-biofilm", "angelsbioprocessinggraphics.alien-pre-artifact-orange&x32")
du.rename("compost", "angelsbioprocessinggraphics.solid-compost&x32")
du.rename("saw", "angelsbioprocessinggraphics.solid-saw")
du.rename("nauvisworm", "worm")
du.rename("nauvisworm-egg-sack", "angelsbioprocessinggraphics.bacteria-anaerobic&x32")
du.rename("rich-soil", "angelsbioprocessinggraphics.solid-soil&x32")
du.rename("phosphoric-fertilizer", "angelsbioprocessinggraphics.solid-fruit&x32")
du.rename("nitrogenous-fertilizer", "angelsbioprocessinggraphics.solid-pips&x32")
du.rename("composter", "composter&x32")
du.rename("worm-meal", "angelsbioprocessinggraphics.cellulose-fiber&x32")
du.rename("green-algae", "angelsbioprocessinggraphics.algae-green&x32")
du.rename("outfall", "angelsrefininggraphics.seafloor-pump-ico&x32")
du.rename("soil-extractor", "%__pycoalprocessinggraphics__/graphics/icons/soil-extractor-mk01.png")
du.rename("blast-furnace", "pycoalprocessinggraphics.hpf")
du.rename("blender", "angelsrefininggraphics.liquifier&x32")
du.rename("shaft", "pyindustrygraphics.niobium-pipe&x32")
du.rename("farm-1", "angelsbioprocessinggraphics.desert-farm&x32")
du.rename("steam-cracker", "angelspetrochemgraphics.separator&x32")
du.rename("crusher-1", "angelsrefininggraphics.ore-crusher")
du.rename("molten-copper", "angelssmeltinggraphics.molten-copper")
du.rename("molten-tin", "angelssmeltinggraphics.molten-tin")
du.rename("molten-bronze", "angelssmeltinggraphics.molten-bronze")
du.rename("molten-lead", "angelssmeltinggraphics.molten-lead")
du.rename("molten-iron", "angelssmeltinggraphics.molten-iron")
du.rename("molten-steel", "angelssmeltinggraphics.molten-steel")
du.rename("molten-stainless-steel", "angelssmeltinggraphics.molten-cobalt-steel")
du.rename("molten-aluminum", "angelssmeltinggraphics.molten-aluminium")
du.rename("molten-silver", "angelssmeltinggraphics.molten-silver")
du.rename("molten-chrome", "angelssmeltinggraphics.molten-chrome")
du.rename("molten-manganese", "angelssmeltinggraphics.molten-manganese")
du.rename("molten-glowing-mangaloy", "angelssmeltinggraphics.molten-brass")
du.rename("molten-molybdenum", "angelssmeltinggraphics.molten-titanium")
du.rename("molten-nickel", "angelssmeltinggraphics.molten-nickel")
du.rename("molten-antimony", "angelssmeltinggraphics.molten-gunmetal")
du.rename("molten-solder", "angelssmeltinggraphics.molten-solder")
du.rename("solder", "angelssmeltinggraphics.solder&x32")