local du = require("dutil")

du.default_copy = true

du.alias("fabricator-1", du.icons("__Krastorio2Assets__/icons/entities/advanced-assembling-machine.png", true), true)
du.alias("counterflow-heat-exchanger", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/classifier.png"}, true)
du.alias("destructive-distillation-tower", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/distilator.png"}, true)
du.alias("glassworks", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/glassworks-mk01.png"}, true)
du.alias("smithy", du.icons{discard=true, name="__pycoalprocessinggraphics__/graphics/icons/advanced-foundry-mk01.png"}, true)
du.alias("oil-refinery", du.icons{discard=true, name="__pypetroleumhandlinggraphics__/graphics/icons/hor-mk01.png"}, true)
du.alias("fuel-refinery", du.icons{discard=true, name="__base__/graphics/icons/oil-refinery.png"}, true)
du.alias("computer-1", du.icons("se/supercomputer-1"), true)
du.alias("computer-2", du.icons("se/supercomputer-2"), true)
du.alias("computer-3", du.icons("se/supercomputer-3"), true)
du.alias("computer-4", du.icons("se/supercomputer-4"), true)
du.alias("processor-1", du.icons("se/laser-laboratory"), true)
du.alias("process", du.icons("se/astronomic-catalogue-4"), true)
du.alias("dead-process", du.icons("se/material-catalogue-4"), true)
du.alias("combustion-generator", du.icons("__Krastorio2Assets__/icons/entities/gas-power-station.png", true), true)
du.alias("crystallizer", du.icons("__pycoalprocessinggraphics__/graphics/icons/desulfurizator-unit.png", true), true)
du.rename("environmental-insight", "se/catalogue/biological-insight")
du.rename("mechanical-insight", "se/catalogue/astronomic-insight")
du.rename("electromagnetic-insight", "se/catalogue/energy-insight")